### ISSUE TITLE
feature request: can you make it clear that a space is public?

### ISSUE THREAD

**Issue by silky** [hyperlink-academy/garden#28]
i only learned by accident that my space can be read by anyone

i don't mind this, in fact it's a feature that i wanted!, but it was a bit surprising (even the list of users joined up.)

could there be a hint on the space that this is the case? it would help others who will be interacting with it be aware of this, and act accordingly!

**Comment by bschlagel** [comment]
Yes good q! I know several folks have mentioned interest in fully private spaces.

I think the simple thing we have in mind here would be a toggle in space settings like public vs private, public being current behavior (anyone can view), private being viewable to members. And membership (needing invite to edit) same as now.

Does that sound like a good solution or something else you had in mind?

**Comment by gchartier** [comment]
I think where the confusion comes in is that because there is no declaration that the space is public, it can be falsely assumed by the user to be private which can be a dangerous assumption depending on what you do with that assumption lol

Support for private spaces would be nice but I think there should at least be a little info message during the space creation process that says something like:
> Note: This is a public space and it will be visible to anyone.

**Comment by bschlagel** [comment]
Thanks @gchartier that makes sense! For now added a little message in the create/edit Space form like so:

> Note: Spaces are publicly viewable.
> Private Spaces are coming soon 🔐🌱
